# -*- coding: utf-8 -*-
"""VGG-16 for image recognition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k1ywPOUsg77SJXedaG8G5sLMY_rM-sLG
"""
# импорт необходимых библиотек
import numpy as np
import matplotlib.pyplot as plt
from tensorflow import keras
from google.colab import files
from io import BytesIO
from PIL import Image

# загрузка модели VGG16
model = keras.applications.VGG16()

# загрузка изображения
uploaded = files.upload()
img = Image.open(BytesIO(uploaded['ex224.jpg']))
plt.imshow( img )

# Предварительная обработка изображения
img = np.array(img)
x = keras.applications.vgg16.preprocess_input(img)
print(x.shape)
x = np.expand_dims(x, axis=0)

# получить вероятности предсказания для каждого класса в результатах классификации модели VGG16
res = model.predict( x )

# получение индекса класса изображения
print(np.argmax(res))
